### PR TITLE
Make rle and openjpeg requirements optional

### LINKED ISSUE #65: Dependency on pylibjpeg-rle
Why does this package depend on pylibjpeg-rle?

1. Run-length encoding is not a JPEG codec.
2. The pylibjpeg-rle requires a Rust compiler, which is not widely available.

I would suggest making pylibjpeg-rle (and probably also pylibjpeg-openjpeg) an extra install requirement (using `extra_requires`).

### PR DESCRIPTION
**Pull request by hackermd**
Fixes #65

### CODE REVIEW

**Review by mrbean-bremen — COMMENTED** [review]
Can you add an entry to the release notes (new file `v1.4.0.rst`)?

**Comment by hackermd** [comment]
> Can you add an entry to the release notes (new file `v1.4.0.rst`)?

Addressed via b313e99eb52dfe96bf7b74efc1c3dced4d232879

**Review by mrbean-bremen — APPROVED** [review]
Thanks!

**Comment by hackermd** [comment]
@mrbean-bremen @scaramallion could we draft a new release and publish an updated package on pypi? Let me know if I can help.

**Comment by scaramallion** [comment]
Sounds good. I was going to hold off because I want to add a v2 interface for the plugins (to remove the Dataset arg requirement) but that can wait.

**Pull request merged**
